O[2023-01-02 15:24:00] [INFO    ] discord.client: logging in using static token
#Traceback (most recent call last):
\  File "/usr/local/lib/python3.11/site-packages/discord/http.py", line 801, in static_login
:    data = await self.request(Route('GET', '/users/@me'))
:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
W  File "/usr/local/lib/python3.11/site-packages/discord/http.py", line 744, in request
(    raise HTTPException(response, data)
Rdiscord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

EThe above exception was the direct cause of the following exception:

#Traceback (most recent call last):
E  File "/home/user_1047945780515852338/main.py", line 4, in <module>
    bot.run_discord_bot()
L  File "/home/user_1047945780515852338/bot.py", line 77, in run_discord_bot
    client.run(TOKEN)
U  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 828, in run
    asyncio.run(runner())
H  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
H  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
/    return self._loop.run_until_complete(task)
/           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
X  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 817, in runner
1    await self.start(token, reconnect=reconnect)
W  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 745, in start
    await self.login(token)
W  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 580, in login
/    data = await self.http.static_login(token)
/           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
\  File "/usr/local/lib/python3.11/site-packages/discord/http.py", line 805, in static_login
C    raise LoginFailure('Improper token has been passed.') from exc
=discord.errors.LoginFailure: Improper token has been passed.